build:
  version: "2.0"

accounts:
  message: "Welcome to MrxBank accounts related QA APIs "
  contactDetails:
    name: "Muthuraja - QA Lead"
    email: "rajamuthu10@gmail.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371