build:
  version: "1.0"

cards:
  message: "Welcome to mrxBank cards related prod APIs "
  contactDetails:
    name: "Muthuraja- Product Owner"
    email: "rajamuthu107@gmail.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721