build:
  version: "2.0"

cards:
  message: "Welcome to mrxBank cards related QA APIs "
  contactDetails:
    name: "Muthuraja - QA Lead"
    email: "rajamuthu107@gmail.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267