build:
  version: "3.0"

cards:
  message: "Welcome to mrxBank cards related local APIs "
  contactDetails:
    name: "Muthuraja - Developer"
    email: "rajamuthu107@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932