build:
  version: "1.0"

loans:
  message: "Welcome to mrxBank loans related prod APIs "
  contactDetails:
    name: "Muthuraja - Product Owner"
    email: "rajamuthu107@gmail.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956